import { CommonColors } from "./colors";
export const Labels = {
  encryptionKey: "uG7@w#9zN!3rL5bE8xT$qF1mZpYcV6Kd",
  login: "Login",
  large: "large",
  register: "Register",
  name: "Full Name",
  continue: "Continue",
  password: "Password",
  deletedSuccessfully: "Deleted Successfully",
  registerNow: "Don't have an account? Register",
  loginNow: "Already have an account? Login",
  loginInfoTitle: "Welcome Back!",
  loginInfoDesc: "Enter to get unlimited access to data & Information.",
  registerInfoTitle: "Hello, Friend!",
  registerInfoDesc: "Enter your details and start your journey with us.",
  date: "Date",
  deleteHolidayConfirmation: "Are you sure you want to delete this holiday?",
  PasswordsDoNotMatch: "Passwords do not match.",
  pleaseFillInAllPasswordFields: "Please fill in all password fields.",
  pleaceEnterFourDigitOtp: "Please enter a valid 4-digit OTP.",
  pleaceEnterYourEmail: "Please enter your email.",
  emailName: "Email",
  email: "Email ID",
  Email: "Email Id",
  inherit: "inherit",
  timeZoneid: "TimeZoneId",
  object: "object",
  activate: "Click to Activate",
  deActivate: "Click to Deactivate",
  clickToActivate: "Click to Activate",
  clickToDeActivate: "Click to Deactivate",
  yes: "Yes",
  no: "No",
  activatedSuccesfully: "Activated Succesfully",
  deActiatetxt: "Are you sure you want to deactivate this organisation?",
  languageid: "LanguageId",
  Organisation_Summary: "Organisation Summary",
  nameEmail: "email",
  editorganisation: "Edit Organisation",
  deActivateOrganisation: "Deactivate Organisation?",
  activateOrganisation: "Activate Organisation?",
  emailError: "Enter valid email",
  underline: "underline",
  mobileNo: "Mobile No",
  mobile: "Mobile",
  disabled: "disabled",
  error: "error",
  editLanguage: "Edit Language",
  addLanguage: "Add Language",
  nameName: "name",
  Confirm: "Yes",
  languageName: "Language",
  languageNameField: "LanguageName",
  active: "Active",
  auto: "auto",
  upload_file: "uploaded_file",
  Confirm_S: "Confirm",
  file: "file",
  nameError: "Enter valid name",
  not_allowed: "not-allowed",
  success: "success",
  warning: "warning",
  pass: "password",
  websiteError: "Please enter a valid website URL",
  txt_Department: "txt_Department",
  txt_autoRespEmailId: "txt_autoRespEmailId",
  txt_EmailSignature: "txt_EmailSignature",
  txt_FilePath: "txt_FilePath",
  ddl_Sla: "ddl_Sla",
  ddl_AlertsTo: "ddl_AlertsTo",
  ddl_NoticesTo: "ddl_NoticesTo",
  ddl_ParentDepartment: "ddl_ParentDepartment",
  ddl_Manager: "ddl_Manager",
  ddl_AutoRespTemplate: "ddl_AutoRespTemplate",
  deActivateHolidayList: "Deactivate Holiday List",
  activateHolidayList: "Activate Holiday List",
  txt_organisationName: "txt_organisationName",
  txt_website: "txt_website",
  txt_emailId: "txt_emailId",
  txt_mobileNo: "txt_mobileNo",
  ddl_languageId: "ddl_languageId",
  ddl_timeZoneId: "ddl_timeZoneId",
  namePassword: "password",
  text: "text",
  false: "false",
  required: "Required",
  dateFormate: "dd MMM yyyy",
  string: "string",
  close: "close",
  closed: "Closed",
  next: "Next",
  center: "center",
  space_between: "space-between",
  backdropClick: "backdropClick",
  z_dialog_title: "z-dialog-title",
  mainHeader: "MAIN_HEADER",
  header: "HEADER",
  subHeader: "SUB_HEADER",
  errorLbl: "ERROR",
  smallText: "SMALL",
  veryVerySmallText: "TINY",
  dashboard: "Dashboard",
  home: "Home",
  master: "Master",
  organisation: "Organisation",
  users: "Users",
  serviceQueue: "Service Queue",
  assignMethod: "Assign Method",
  businessHours: "BusinessHours",
  ticketDashboard: "Ticket Dashboard",
  xxxxs: "10px",
  xxs: "12px",
  xs: "14px",
  sm: "16px",
  lg: "18px",
  xl: "20px",
  xxl: "35px",
  xxxl: "50px",
  bold: "bold",
  big: "big",
  semiBold: "semiBold",
  medium: "medium",
  regular: "regular",
  normal: "normal",
  maxWidth: {
    sm: "sm",
    md: "md",
  },
  add: "Add",
  assignmethodtoast: "Delete Sucessfully!",
  addedDepartment: "Department updated successfully!",
  updatedDepartment: "Department created successfully!",
  activateDepartment: "Activate Department?",
  activateVariable: "Activate Variable",
  addedVariable: "Template variable added successfully",
  activateConfirmVariable: "Are you sure want to activate this template variable?",
  addTemplateVarible: "Add Template Variable",
  activateVariableSuccessMsg: "Template variable activated successfully",
  actions: "Actions",
  actionsField: "actions",
  activateLanguage: "Activate language",
  autoRespEmailField: "AutoRespEmailId",
  autoRespEmailHeader: "Auto Resp Email Id",
  back: "Back",
  businessHoursName: "Business Hours Name",
  buisnessHoursType: "BuisnessHours Type",
  bar: "bar",
  bottom: "bottom",
  right: "right",
  borderRadious: {
    sm: "12px",
    md: "14px",
    lg: "20px",
  },
  buisnessHours: "Buisness Hours",
  button: "button",
  blur: {
    blur4px: "blur4px",
  },
  contained: "contained",
  captchaError: "Captcha does not match",
  clear: "Clear",
  chooseLogo: "chooseLogo",
  createdByField: "createdBy",
  createdByHeader: "Created By",
  cancel: "Cancel",
  checkbox: "checkbox",
  chooseFile: "Choose file",
  createAccount: "Create Your Account",
  cursor: {
    pointer: "pointer",
  },
  classNames: {
    pageContainer: "page-container",
    navbar: "navbar",
    navbarLeft: "navbar-left",
    navbarLogo: "navbar-logo",
    sidebar: "sidebar",
    sidebarExpanded: "sidebar-expanded",
    sidebarCollapsed: "sidebar-collapsed",
    sidebarBg: "sidebar-bg",
    sidebarContent: "sidebar-content",
    sidebarLink: "sidebar-link",
    sidebarLinkText: "sidebar-link-text",
    sidebarSubmenu: "sidebar-submenu",
    sidebarItem: "sidebar-item",
    sidebarItemText: "sidebar-item-text",
    mainContent: "main-content",
    mainInner: "main-inner",
    footer: "footer",
  },
  cb_isActive: "cb_isActive",
  cb_isVisible: "cb_isVisible",
  cbl_IsPublic: "cbl_IsPublic",
  cbl_IsVisible: "cbl_IsVisible",
  cbl_IsActive: "cbl_IsActive",
  Comments: "Comments",
  confirmDate: "Confirm Dates",
  confirmPassword: "Confirm Password",
  confirmDelete: "Confirm Delete",
  catchErrorMsg: "Something went wrong",
  clickToAdd: "Click here to add",
  changeDates: "Change Dates",
  confirmDeactivateLanguage: "Are you sure want to deactivate language?",
  confirmActivateLanguage: "Are you sure want to activate language?",
  category: "Category",
  doughnut: "doughnut",
  discription: "Description",
  days: {
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
  },
  activateConfirmDepartment: "Do you want to activate this department?",
  deleteUser: "Delete User?",
  dropdown: "dropdown",
  department: "Department",
  div: "div",
  display: {
    flex: "flex",
    block: "block",
    grid: "grid",
    absolute: "absolute",
    inline_block: "inline-block",
    inline_flex: "inline-flex",
  },
  deleteUserMessage: "Are you sure you want to make avtive this user? ",
  darktext: "dark:text-white",
  departmentForm: "Department Form",
  deactivateLanguage: "Deactivate language",
  DepartmentLabels: {
    departmentMandatory: "Department *",
    parentDepartment: "Parent Department",
    manager: "Manager *",
    emailId: "Email ID *",
    autoRespEmailId: "Auto Resp Email Id *",
    autoRespTemplate: "Auto Resp. Template *",
    emailSignature: "Email Signature *",
    sla: "SLA *",
    alertsTo: "Alerts To *",
    noticesTo: "Notices To *",
    filePath: "File Path *",
    isPublic: "Is Public",
    isVisible: "Is Visible",
    isActive: "Is Active",
    isManager: "isManager",
    clear: "Clear",
    submit: "Submit",
    successMessage: "Department created successfully",
    failureMessage: "Failed to submit",
  },
  dropdownErrorMsg: "Failed to fetch dropdown values",
  dropdownError: "An error occurred when fetching dropdown values",
  deleteConfirmationMsg: "Are you sure you want to deactivate this department?",
  deleteDialog: "deleteDialog",
  activeDialog: "activeDialog",
  deactivateVariable: "Deactivate Variable",
  deactivateVariableSuccessMsg: "Template variable deactivated successfully",
  deactivateConfirmVariable: "Are you sure want to deactivate this template variable?",
  departmentSummary: "Department Summary",
  deleteDepartment: "Deactivate Department?",
  departmentName: "Department Name",
  enterEmail: "Enter Email",
  edit: "Edit",
  enterCaptcha: "Enter Captcha",
  emailOrPhone: "Email/Phone",
  emailPlaceholder: "example@gmail.com",
  emailAddress: "Email Address",
  enterYourNoteHere: "Enter your note here...",
  editTicket: "Edit Ticket",
  createNewTicket: "Create New Ticket",
  fourHundredPixel: "400px",
  firstWeekDay: "First Week Day",
  firstWeekOff: "First Week Off",
  firstWeekDayField: "FirstWeekDay",
  firstWeekOffField: "FirstWeekOff_Days",
  fields: {
    txt_BusinessHoursName: "txt_BusinessHoursName",
    ddl_BusinessHourType: "ddl_BusinessHourType",
    ddl_TimeZone: "ddl_TimeZone",
    ddl_FirstWeekDay: "ddl_FirstWeekDay",
    ddl_FirstWeekOff: "ddl_FirstWeekOff",
    ddl_SecondWeekOff: "ddl_SecondWeekOff",
    ddl_ThirdWeekOff: "ddl_ThirdWeekOff",
    ddl_FourthWeekOff: "ddl_FourthWeekOff",
    ddl_FifthWeekOff: "ddl_FifthWeekOff",
    ddl_HolidayList: "ddl_HolidayList",
    cb_IsActive: "cb_IsActive",
  },
  forgotPassword: "ForgotPassword?",
  function: "function",
  fourthWeekOff: "Fourth Week Off",
  fifthWeekOff: "Fifth Week Off",
  fourthWeekOffField: "FourthWeekOff_Days",
  fifthWeekOffField: "FifthWeekOff_Days",
  failedTosendOtp: "Failed to send OTP",
  flag: {
    updatePassword: "UpdatePassword",
    verify: "Verify",
    insert: "I",
    update: "U",
    select: "S",
    edit: "E",
    delete: "D",
    active: "A",
    activate: "ACTIVATE",
    deActiate: "DEACTIVATE",
    admin: "ADMIN",
    visible: "VISIBLE",
    public: "PUBLIC",
    agent: "AGENT",
    generateOtp: "GenerateOtp",
  },
  fieldset: "Fieldset",
  firstName: "FirstName",
  fullWidth: "100%",
  failToLoadDepartment: "Fail to load department details",
  fromDate: "FromDate",
  from: "From",
  goAhead: "Go Ahead",
  gender: "Gender",
  genderField: "gender",
  getcolumnfield: "assignmethod",
  getcolumnField: "Assign Method",
  hi: "Hi",
  holiday: "Holiday",
  holidayList: "Holiday List",
  holidayListName: "Holiday List Name",
  holidayName: "Holiday Name",
  addHolidayList: "Add Holiday List",
  editHolidayList: "Edit Holiday List",
  updateHoliday: "Holiday updated successfully!",
  addedHoliday: "Holiday added successfully!",
  updateHolidayError: "Failed to update holiday",
  addHolidayError: "Failed to add holiday",
  deleteHoliday: "Holiday deleted successfully!",
  deleteHolidayError: "Failed to delete holiday.",
  editHoliday: "Edit Holiday",
  addHoliday: "Add Holiday",
  holidayListField: "HolidayListName",
  noOfHolidaysField: "NoOfHolidays",
  noOfHolidaysHeader: "No. of Holidays",
  holidayNameField: "HolidayName",
  hobbies: "Select Hobbies",
  hoverShadow: "0 0 0 3px ${color}22",
  boxShadow: `0 0 0 3px ${CommonColors.fallback_solid}22`,
  boxShadow1: "0 2px 10px rgba(0, 0, 0, 0.05)",
  boxShadow2: `0 0 0 2px ${CommonColors.fallback_solid}33`,
  invalidUserMessage: "Email or number does't exist",
  isActive: "Is Active",
  isAdmin: "Is Admin",
  isAgent: "Is Agent",
  isVisible: "Is Visible",
  isManager: "Is Manager",
  isActiveField: "IsActive",
  isPublicField: "IsPublic",
  isVisibleField: "IsVisible",
  id: "id",
  left: "left",
  lastLogin: "Last Login",
  language: "Language",
  lastName: "LastName",
  legend: "legend",
  logo: "logo",
  lastupdateField: "lastUpdated",
  lastupdateHeader: "Last Updated",
  languageSummary: "Languages",
  mandatoryStar: "*",
  mobileOrEmail: "Mobile/Email",
  makeInactive: "Make InActive?",
  makeActive: "Make Active?",
  makeActiveMessage: "Are you sure you want to make avtive this user? ",
  makeInactiveNote: "Are you sure you want to make this inActive? ",
  makeActiveNote: "Are you sure you want to make this avtive  ? ",
  manager: "Manager",
  notACustomerPostYourQuerry: "Not a customer? post your query now!!",
  Notifications: "Notifications",
  noDataFound: "No Data Found",
  num_0: 0,
  num_fourHundred: 400,
  num_fiveHundred: 500,
  num_sixHundred: 600,
  num_50: 50,
  num_300: 300,
  num_3000: 3000,
  num_500: 500,
  num_1000: 1000,
  num_1500: 1500,
  num_6000: 6000,
  num_10: 10,
  num_8: 8,
  num_point5: 0.5,
  num_sevenHundered: 700,
  nameEmailOrPhone: "emailOrPhone",
  nameCaptcha: "captcha",
  none: "none",
  newPassword: "New Password",
  number: "Number",
  noHolidaysFound: "No Holidays Found",
  noNotes: "No notes added yet",
  noAttachments: "No attachments added yet",
  note: "Note",
  organization: "Organization",
  outlined: "outlined",
  OrganisationLabels: {
    title: "Organisation",
    ChooseLogo: "chooseLogo",
    errororglist: "Failed to load organisation list",
    ChooseFavicon: "chooseFavicon",
    organisationName: "Organisation Name",
    addOrganisation: "Add Organisation",
    createOrganisation: "Organization created successfully",
    updateOrganisation: "Organization updated successfully",
    update: "Update",
    errorfetching: "Error fetching organisation:",
    website: "Website",
    emailId: "Email",
    data: "data:",
    mobileNo: "Mobile Number",
    dbactive: "Are you sure you want to activate this organisation?",
    language: "Language",
    logoLink: "Logo Link",
    chooseLogo: "Logo Upload",
    chooseFavicon: "Favicon Upload",
    isVisible: "Is Visible",
    clear: "Clear",
    submit: "Submit",
    errorinorgid: "Error fetching organisation by ID:",
    successMessage: "Organisation saved successfully!",
    failureMessage: "Failed to save organisation",
    onlyImageFilesAllowed: "Only image files are allowed",
    formSubmissionError: "An error occurred while submitting the form",
    submissionErrorLog: "Submission error:",
    errorloading: "Error loading organization details",
    img: "image/",
    dderror: "Error loading dropdown options",
    fileUpload: {
      noFileSelected: "No file selected",
      uploadButton: "Upload",
      removeButton: "Remove",
      fileTooLarge: "File size must be less than {size}MB",
      invalidType: "Only {types} files are allowed",
      preview: "Preview",
      dragAndDrop: "Drag & drop files here or",
      browseFiles: "browse files",
      maxFiles: "Maximum {count} files allowed",
      fileNameTruncated: "{name}...",
    },
    imageUpload: {
      logo: {
        label: "Logo",
        placeholder: "Upload organization logo",
        dimensions: "Recommended dimensions: 250x250px",
        size: "Max size: 2MB",
        formats: "Formats: PNG, JPG, SVG",
      },
      favicon: {
        label: "Favicon",
        placeholder: "Upload favicon",
        dimensions: "Recommended dimensions: 32x32px",
        size: "Max size: 1MB",
        formats: "Formats: ICO, PNG",
      },
    },
  },
  opt_music: "music",
  opt_sports: "sports",
  opt_Read: "reading",
  opt_male: "Male",
  opt_female: "Female",
  opt_other: "Other",
  operationFailed: "Operation failed",
  passwordMismatch: "Your passwords are not identical",
  postYourQuery: "Post your query",
  namePostYourQuery: "query",
  passwordPlaceholder: "********",
  phoneNo: "PhoneNo",
  percentage: {
    per_100: "100%",
    per_neg100: "-100%",
    per_0: "0%",
  },
  padding: {
    xsmall: "8px 12px",
    small: "6px 16px",
    default: "10px 22px",
  },
  priority: "Priority",
  rem: {
    rem_point875: "0.875rem",
    rem_point75: "0.75rem",
  },
  query: "Query",
  registrationSuccessfull: "Your Query raised successfully",
  Reload: "Reload",
  resetPassword: "Reset Password",
  reset: "Reset",
  role: "Role",
  reportingTo: "Reporting To",
  signInToQms: "SignIn ",
  status: "Status",
  statusField: "status",
  secondWeekOffField: "SecondWeekOff_Days",
  sla: "SLA",
  selectHoliday: "Select Holiday Dates",
  selectHolidayList: "Select a holiday list to view holidays",
  secondWeekOff: "Second Week Off",
  submit: "Submit",
  sendOtp: "Send OTP",
  signature: "Signature",
  start: "start",
  signIn: "SignIn",
  small: "small",
  sucess: "success",
  shadow: "0 4px 12px rgba(0,0,0,0.12)",
  select: "Select",
  res: {
    status: "S",
    message: "Success",
    success: "success",
    error: "error",
  },
  summary: "summary",
  ticketForm: {
    txt_summary: "txt_summary",
    ddl_priority: "ddl_priority",
    ddl_severity: "ddl_severity",
    Query: "Query",
    Priority: "Priority",
    Severity: "Severity",
  },
  ticketNo: "Ticket No",
  ticketDate: "ticketDate",
  ticketPreview: "Ticket Preview",
  templateGroupDiscription: "Template Description",
  templateToaster: {
    insert: "Template created successfully!",
    update: "Template updated successfully!",
    failure: "Failed to save template",
    success: "Template saved successfully!",
  },
  templateGroupDiscField: "TemplateGroupDiscription",
  templateGroup: "Template Group",
  templates: "Template",
  templateName: "Template Name",
  templateDisc: "TemplateDescription",
  thirdWeekOffField: "ThirdWeekOff_Days",
  thirdWeekOff: "Third Week Off",
  top: "top",
  txt_EmailId: "txt_EmailId",
  txt_logoLink: "txt_logoLink",
  txt_AutoRespEmailId: "txt_AutoRespEmailId",
  timeZone: "Time Zone",
  timeZoneName: "TimeZoneName",
  txt_TemplateGroupName: "txt_TemplateGroupName",
  txt_TemplateDiscription: "txt_TemplateDiscription",
  templateDiscription: "Template Description",
  txt_TemplateName: "txt_TemplateName",
  templateGroupName: "Template Group Name",
  txt_Language: "txt_Language",
  txt_TemplateGroupDiscription: "txt_TemplateGroupDiscription",
  templateVariable: "Template Variables",
  type: {
    button: "button",
  },
  textFieldWitdh: {
    medium: "300px",
  },
  textFieldBorderColor: {
    white: "#d1d5db",
  },
  inputField: "textField",
  textField: {
    fontColor: "#111827",
    labelColor: "#374151",
  },
  transition: "all 0.3s ease",
  toDate: "ToDate",
  to: "To",
  ticket: "Ticket",
  ticketsByPriority: "Tickets by Priority",
  ticketsByStatus: "Tickets by Status",
  ticketIcon: "Ticket Icon",
  update: "Update",
  unlock: "Unlock",
  userFormTitle: "User Form",
  userName: "User Name",
  usersFormName: {
    txt_firstName: "txt_firstName",
    txt_lastName: "txt_lastName",
    dd_department: "dd_department",
    dd_role: "dd_role",
    dd_reportingTo: "dd_reportingTo",
    txt_password: "txt_password",
    txt_email: "txt_email",
    txt_mobileNo: "txt_mobileNo",
    txt_phoneNo: "txt_phoneNo",
    txt_signature: "txt_signature",
    dd_language: "dd_language",
    dd_timeZone: "dd_timeZone",
    dd_organization: "dd_organization",
    isActive: "isActive",
    isAdmin: "isAdmin",
    isVisible: "isVisible",
    isAgent: "isAgent",
    isManager: "isManager",
  },
  userSummary: "User Summary",
  updateVariable: "Template variable updated successfully",
  verifyOtp: "Verify OTP",
  variant: {
    filled: "filled",
    outlined: "outlined",
    contained: "contained",
    body1: "body1",
  },
  varnameField: "varName",
  varnameHeader: "TMPL var name",
  vartypeField: "varTypeId",
  vartypeHeader: "Var type",
  varvalueField: "varValue",
  varvalueHeader: "Var value",
  wrongPassword: "Wrong password",
  welcome: "Welcome Back!",
  weekStarts: "Week Starts",
  weekList: {
    first: "1st WK",
    second: "2nd WK",
    third: "3rd WK",
    fourth: "4th WK",
    fifth: "5th WK",
  },
  width: {
    px_360: "300px",
    px_14: "14px",
    px_12: "12px",
  },
  xsmall: "xsmall",
  yourSessionIsExpired: "Your session is expired",
  yourTickets: "Your Tickets",
  zTable: {
    blue: "#23A9F2",
    gray: "#e0e0e0",
    inherit: "#757575",
    green: "#28A745",
    red: "#DC3545",
    orange: "#FFA500",
  },
  zoiFintech: "ZOI FINTECH SERVICES",
  zoiFintechFooter: " © Zoi Fintech 2025–2026",
  ticketIconAlt: "Ticket Icon",
  goBack: "Go back",
  additionalInfo: "Additional Info",
  description: "Description",
  noDescription: "No description provided",
  noNotesAdded: "No notes added yet",
  attachments: "Attachments",
  notes: "Notes",
  raisedBy: "Raised By:",
  responseDue: "Response Due:",
  viaMobile: "via mobile",
  assigned: "Assigned",
  assignedTo: "Assigned To",
  Critical: "Critical",
  High: "High",
  Normal: "Normal",
  Low: "Low",
  raiseYourQueryNow: "Raise your query now!",
  dash: "-",
  empty: "",
  ticketIdPrefix: "#TC- ",
  dateTimeFormat: "MMMM D, YYYY - HH:mm",
  dueIn: "Due in",
  minute: "minute",
  mins: "mins",
  attachmentsCount: "attachment(s)",
  DeleteDialog: "Are you sure you want to delete this Assign Method?",
  RestoreDialog: "Are you sure you want to restore this Assign Method?",
  DServiceDialog: "Are you sure you want to delete this Service Queue?",
  RServiceDialog: "Are you sure you want to restore this Service Queue?",
  DEmailServerDialog: "Are you sure you want to delete this Email Server?",
  REmailServerDialog: "Are you sure you want to restore this Email Server?",
  DAgentDialog: "Are you sure you want to delete this Agent Detail?",
  RAgentDialog: "Are you sure you want to restore this Agent Details?",
  titleDelete: "Confirm Delete",
  titleRestore: "Confirm Restore",
  delete: "delete",
  restore: "restore",
  Delete: "Delete",
  Cancel: "cancel",
};